config/routes.rb
Rails.application.routes.draw do

  get 'city/show'
  get 'user/show'
  root 'home#index'

  get '/team', to: 'team#show'

  get '/contact', to: 'contact#show'

  get '/welcome/:first_name', to: 'welcome#say_hello', as: 'landing'

  resources :gossips do
    resources :like, only: [:new, :create, :destroy]
  end
  resources :user

  resources :city

  resources :comment 

  resources :sessions, only: [:new, :create, :destroy]

  #resources :like, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    has_many :tags, through: :gossip_tags
    belongs_to :user
    has_many :comments

    has_many :like

    validates :title,
    presence: true,
    length: { in: 3..14 }

    validates :content,
    presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
  end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/pm_user.rb
class PmUser < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :recipient, class_name: "User", through: :pm_users
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments
    has_many :like
    has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = User.where(city: @city)
   @gossips = Gossip.where(user: @users)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index, :show, :create, :new]
  before_action :is_user, only: [:edit, :update, :destroy]

  def show
    id = params[:id]
    @gossipfind = Gossip.find(params[:id])
    @user = @gossipfind.user
    @city = @user.city
    @gossip_edit = Gossip.find(params[:id])
    @comments = @gossipfind.comments
    @comment = Comment.new

    @gossiptags = GossipTag.where(gossip_id: @gossipfind.id)
    
    @tags = Tag.where(tag_id: @gossiptags)
   end



  def index
    @gossips = Gossip.all
  end



  def new
    @tags = Tag.all
    @gossip = Gossip.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    @gossip = Gossip.create('title' => params[:title],
                            'content' => params[:content],
                            'create_date' => '2017-09-23',
                            'user_id' => session[:user_id])
    if @gossip.save
    redirect_to gossip_path(@gossip.id)
    flash[:notice_good] = "Gossip Crée"
      else 
        flash[:notice_bad] = "Creation avortée"
        render 'new'
       
      end 
     
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end 


  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition

  @gossip_edit = Gossip.find(params[:id])
  end

  def update

    @gossip = Gossip.find(params[:id])        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    post_params = params.require(:gossip).permit(:title, :content) 
    @gossip.update(post_params) 


    if @gossip.update(post_params)
      redirect_to gossip_path(@gossip.id)
      flash[:notice_good] = "Edition reussis !"
    else 
      redirect_to gossip_path(@gossip.id)
      flash[:notice_bad] = "Probleme rencontré"
      
     
    end 
   
  end

  def destroy

    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

private




def authenticate_user
  unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
  end
end

def is_user
  @gossip = Gossip.find(params[:id])
unless current_user.id == @gossip.user_id
  flash[:danger] = "Please log in."
  redirect_to root_path
end
end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
    def user_is?
        @gossip = Gossip.find(params[:id])
     current_user.id == @gossip.user_id
     
      end
      
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        end

        def current_user
            User.find_by(session[:user_id])
          end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<h1> Edit</h1>


<% if flash[:notice_good] %>
<div class="alert alert-success" role="alert">
  A simple success alert—check it out!
</div>
 <% end %>


 
<%= form_for @gossip_edit do |f| %>
    <div class="form_group">
        <label>Titre</label>
        <%= f.text_field :title, class: 'form_control' %>
    </div>

    <div class="form_group">
        <label>Titre</label>
        <%= f.text_area :content, class: 'form_control' %>
    </div>

    <div class="form_group">
        <label>Titre</label>
        <button typ='submit'>Modifier l'article</button>>
    </div>

    <% end %>

app/views/gossips/new.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>The Gossip Project - Create</title>
</head>

<body>
<h1> Bienvenue sur la page de création d'un potin</h1>


   <% if flash[:notice_bad] %>
<div class="alert alert-danger" role="alert">
 Creation du Gossip annulée: titre trop long ou inexistant
</div>
  <% end %>


<br>
<br>
<br>
<br>
<br>
<br>

<%= form_tag url_for(action: 'create'), method: "post" do %>
<div id="container">
<form>
  <div class="row">
    <div class="col">
        <%= label_tag 'Titre' %> <br />
        <%= text_field_tag 'title', @gossip.title, class: "form-control", placeholder: 'Un titre sympa', autocomplete: 'off' %>
        <br /> <br />
    </div>
<div class="col">
        <%= label_tag 'Contenu' %> <br />
        <%= text_field_tag 'content', @gossip.content, class: "form-control", placeholder: 'Votre potin', autocomplete: 'off'%>
    </div>
  </div>
<label for="tags">Tag: </label>
<select id="tags" name="taglist" form="tagform">
<% @tags.each do |f| %>
  <option value=<% f.title %>><%= f.title %></option>  <!-- A REVOIR LE VALUE -->
  <% end %>
</select>
        <br /> 
         


        <%= submit_tag "Create Gossip", class: "btn btn-info" %>  <%= link_to "Revenir à l'accueil", root_path, :class => 'btn btn-secondary'%>
</div>
      <% end %>

        </form>

</div>
</div>
</div>
<br>
<br>

</body>

</html> 

app/views/gossips/show.html.erb
<!doctype html>
<html lang="fr">
<!-- HEADER -->
<head>
  <meta charset="utf-8">
  <title><%= "The Gossip Project" %></title>
  <script src="script.js"></script>
</head>
<body>
   <% if flash[:notice_good] %>
<div class="alert alert-success" role="alert">
  A simple success alert—check it out!
</div>
 <% end %>
<!-- CARD -->
<div class="card card-cascade wider reverse">

  <!-- IMAGE -->
  <div class="view view-cascade overlay">
    <img class="card-img-top" src="https://www.avenir-sante.com/wp-content/uploads/2018/11/gossip-time-nico.png"
      alt="Card image cap">
    <a href="#!">
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>

  <!-- CONTENT -->
  <div class="card-body card-body-cascade text-center">

    <!-- TITLE -->
    <h2 class="card-title"><strong><%= @gossipfind.title%></strong></h2>
 
    <!-- AUTEUR -->
    <h4 class="font-weight-bold py-2"> By <%= @gossipfind.user[:first_name]%> </h4> <p>From <%= link_to "#{@city[:name]}", city_path(@city[:id])  %> </p>

    <!-- TEXT -->
    <p class="card-text"><%= @gossipfind.content%>
    </p>

    <p>ecris le <%= @gossipfind.create_date.strftime("%d/%m/%Y")%></p>
<p><%= @gossipfind.like.count %> <%= (@gossipfind.like.count) == 1 ? 'Like' : 'Likes'%></p>
   <!--  <%= button_to 'Like', gossip_like_index_path(@gossipfind.id), method: :post %>
    <%= button_to 'Unlike', gossip_like_path(@gossipfind), method: :delete %>-->
<% if logged_in? == true %>
    <% pre_like = @gossipfind.like.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', gossip_like_path(@gossipfind, pre_like), method: :delete , :class => "btn btn-success btn-sm active"%>
<% else %>
  <%= button_to 'Like', gossip_like_index_path(@gossipfind), method: :post , :class => "btn btn-success btn-sm active"%>
<% end %>
<% end %>
    <%= link_to "Accéder au pofil de #{@gossipfind.user[:first_name]}", user_path(@gossipfind.user[:id]), :class => "btn btn-outline-dark btn-lg" %>
  
     <!-- AJOUT COMMENTAIRE -->
  <%= form_tag '/comment', method: "post" do %>
<div id="container">
<form>
  <div class="row">
    <div class="col">
<div class="col">
        <%= label_tag 'Contenu' %> <br />
        <%= text_field_tag 'content', @comment.content, class: "form-control", placeholder: 'Commentaire', autocomplete: 'off'%>
        <input name="gossip_id" type="hidden" value=" <%= @gossipfind.id %>">
    </div>
  </div>

        <br /> 

</div>
        <%= submit_tag "Confirmer", class: "btn btn-lg btn-info" %>  

</div>
      <% end %>


     <!-- COMMENTAIRES -->
     <% @comments.each do |com|%>
<div class="row">

<div class="card text-left m-5" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= com.content%></h5>
      <p class="card-text"><%= com.user[:first_name]%></p>
       <% if user_is? == true %>               <!-- !!!!!!!!!!!!!!!!!!!!!!!! A lié avec l'user_id du comment -->
      <%= link_to "Voir le commentaire", edit_comment_path(com.id), :class =>"btn btn-secondary btn-lg active" %>
      <% end %>
    </div>
  </div>
  </div>
  <%end%>
  
<%= link_to "Commenter", new_comment_path, :class =>"btn btn-info btn-lr active" %>

  </div>
   <!-- <%= link_to "Editer le Gossip", edit_gossip_path(@gossipfind.id), :class =>"btn btn-secondary btn-lr active" %>   -->     
</div>


 <!-- MODAL -->
 <% if user_is? == true %>
   <%= form_for @gossipfind do |f| %>
<button type="button" class="btn  btn-info" data-toggle="modal" data-target="#exampleModal" data-whatever="Titre">Editer</button>
<br>
 <!-- <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal" data-whatever="Titre">Supprimer</button>-->    

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modifie ton gossip</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
            <div class="form_group">
        <label>Titre</label>
        <%= f.text_field :title, class: 'form_control' %>
    </div>
            <div class="form_group">
        <label>Titre</label>
        <%= f.text_area :content, class: 'form_control' %>
    </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" <%=form_tag url_for(action: 'update'), method: "post" do %>> Sauvegarder</button>
      </div>
    </div>
  </div>
</div>
 <% end %>
 <% end %>
 <%= button_to "Supprimer", @gossip, :method => :delete, data: {confirm: "T'es sur ?"}, :class => 'btn btn-danger'%>   <!-- FAIRE LA CONFIRMATION -->
<% end %>
        <%= link_to "Revenir à l'accueil", root_path, :class => 'btn btn-larg btn-secondary'%>
 <%= link_to "Signaler", edit_gossip_path(@gossipfind.id), :class =>"btn btn-danger btn-sm active" %>
<!-- <a href="<%= edit_gossip_path(@gossipfind.id)%>" class="btn">Voir l'article</a>                             edit_gossip_path(@gossipfind.id)-->



</body>
</html>