config/routes.rb
Rails.application.routes.draw do

  get 'city/show'
  get 'user/show'
  root 'home#index'

  get '/team', to: 'team#show'

  get '/contact', to: 'contact#show'

  get '/welcome/:first_name', to: 'welcome#say_hello', as: 'landing'

  resources :gossips do
    resources :like, only: [:new, :create, :destroy]
  end
  resources :user

  resources :city

  resources :comment 

  resources :sessions, only: [:new, :create, :destroy]

  #resources :like, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    has_many :tags, through: :gossip_tags
    belongs_to :user
    has_many :comments

    has_many :like

    validates :title,
    presence: true,
    length: { in: 3..14 }

    validates :content,
    presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
  end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/pm_user.rb
class PmUser < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :recipient, class_name: "User", through: :pm_users
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments
    has_many :like
    has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = User.where(city: @city)
   @gossips = Gossip.where(user: @users)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
    def user_is?
        @gossip = Gossip.find(params[:id])
     current_user.id == @gossip.user_id
     
      end
      
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        end

        def current_user
            User.find_by(session[:user_id])
          end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title><%= "The Gossip Project" %></title>
  <script src="script.js"></script>
</head>
<body>
<br>
<h1> Profil </h1>
<!-- Card -->
<div class="card testimonial-card">

  <!-- Background color -->
  <div class="card-up indigo lighten-1"></div>
<br>
  <!-- Avatar -->
  <div class="avatar mx-auto white">
    <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle"
      alt="woman avatar">
  </div>

  <!-- Content -->
  <div class="card-body">
    <!-- Name -->
    <h3 class="card-title"><%="#{@city.name}"%></h3>
    <hr>
    <div class="row">
  <% @gossips.each do |goss|%>
<div class="row">
<!-- creation mini carte gossip -->
<div class="card text-left m-5" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= goss.title%></h5>
      <p class="card-text"><%= goss.user[:first_name]%></p>
      <p class="card-text"><small class="text-muted"><%= goss.create_date.strftime("%d/%m/%Y")%></small></p>
      <%= link_to "Accéder au gossip", gossip_path(goss.id), :class =>"btn btn-secondary btn-lg active" %>
      <p><%= goss.like.count %> <%= (goss.like.count) == 1 ? 'Like' : 'Likes'%></p>
      <p class="card-text"> <%= goss.comment_ids.count%> commentaires</p>
      <% if logged_in? == true %>
<% pre_like = goss.like.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
         <%= button_to 'Unlike', gossip_like_path(goss, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', gossip_like_index_path(goss), method: :post %>
<% end %>
<% end %>
    </div>
  </div>
  </div>
      <% end %>
    <!-- Quotation -->
    <p>
    </p>
    <%= link_to "Revenir à l'accueil", landing_path(:first_name_id), :class => 'btn btn-info'%>
  </div>
</div>

</div>

</div>
<!-- Card -->
</body>
</html>