config/routes.rb
Rails.application.routes.draw do

  get 'city/show'
  get 'user/show'
  root 'home#index'

  get '/team', to: 'team#show'

  get '/contact', to: 'contact#show'

  get '/welcome/:first_name', to: 'welcome#say_hello', as: 'landing'

  resources :gossips do
    resources :like, only: [:new, :create, :destroy]
  end
  resources :user

  resources :city

  resources :comment 

  resources :sessions, only: [:new, :create, :destroy]

  #resources :like, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    has_many :tags, through: :gossip_tags
    belongs_to :user
    has_many :comments

    has_many :like

    validates :title,
    presence: true,
    length: { in: 3..14 }

    validates :content,
    presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
  end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/pm_user.rb
class PmUser < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :recipient, class_name: "User", through: :pm_users
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    has_many :comments
    has_many :like
    has_secure_password
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
    def user_is?
        @gossip = Gossip.find(params[:id])
     current_user.id == @gossip.user_id
     
      end
      
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        end

        def current_user
            User.find_by(session[:user_id])
          end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <a class="navbar-brand" href="http://localhost:3000/welcome/correcteur">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class =>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Team", team_path, :class =>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, :class =>"nav-link" %>
      </li>
      <li class="nav-item dropdown">
     
      </li>
    </ul>
<% if logged_in? == false %>
       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Utilisateur
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <p> <%= link_to "Se connecter", new_session_path, :class =>"dropdown_item" %></p>
          <%= link_to "S'inscrire'", new_user_path, :class =>"dropdown_item" %>
        </div>
 <%end%>
<% if logged_in? == true %>
      <%= link_to "Se déconnecter", session_path(session.id), method: :delete, :class =>"btn btn-dark my-2 my-sm-0"%>
      <%end%>
  </div>
</nav>
    <%= yield %>
  


    <footer class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://www.facebook.com/chris.boyer.7359"> Chris => christeufeur83@gmail.com</a>
  </div>
  <!-- Copyright -->

</footer>
  </body>
</html>